### ISSUE TITLE
各バッチに関する質問

### ISSUE THREAD

**Issue by tomo-nagae** [Personal-Data-Linkage-Module/pxr-ver-1.0#16]
# 状況
以前のセミナーでいただいたバッチについて調査しているのですが、いくつか質問事項が発生しました。
内容についてご教授いただけないでしょうか。

# 質問事項

## Region改定再同意依頼バッチ
1. PxR側の実装を見ると、規約がPF利用規約の場合の分岐も存在するようです。
  例えば、pxr-book-manageのTermsOfUseService.ts#getTermsOfUseTargetFind() の処理で分岐が存在します。
  本バッチでPF利用規約更新時の再同意依頼処理もまかなえる理解でよろしいでしょうか。
  または、PF利用規約用のバッチ開発が必要となるのでしょうか。
2. バッチとは異なるかもしれませんが、規約更新時に個人に規約再同意を促すフローはあるのでしょうか。
    メール or SMSで通知するフローを想定しておりますが、実装が必要となる場合、どの部分になりますでしょうか。

## Book自動閉鎖バッチ
1. 本バッチが動作した場合、対象の個人のデータは削除されない認識であっておりますでしょうか。
2. 自動閉鎖された個人の復帰方法についてご教授いただけないでしょうか。

## Region利用自動終了対象追加バッチ
1. 本バッチが動作した場合、対象の個人のデータは削除されない認識であっておりますでしょうか。
2. 自動終了された個人の復帰方法についてご教授いただけないでしょうか。

## Region利用自動終了バッチ
1. 本バッチは「Region利用自動終了対象追加バッチ」と「Region終了対象追加バッチ」の実行でRegion終了対象となった個人に対して動作する認識でよろしいでしょうか。  

## 出力データファイル管理作成バッチ
1. 本バッチが動作するユースケースについてご教授いただけないでしょうか。
    どのように動作するかフローを確認できればと思います。
2. 出力データファイル作成・取得するフローは存在するのでしょうか。

## Region終了対象追加バッチ
1. 本バッチは以下のAPI実行後に動作する認識であっておりますでしょうか。
   * Region終了要求：POST /catalog-update/region/status/end
   * 承認: PUT /notification/approval

## Region利用終了バッチ
1. 本バッチは「Region終了対象追加バッチ」実行後の結果により動作する認識であっておりますでしょうか。

**Comment by itoshot** [comment]
@tomo-nagae 
各バッチ毎に個別のIssueを挙げていただけますでしょうか？
個別にご質問を頂けますと回答や修正のトレーサビリティが向上しますのでよろしくお願いいたします。

**Comment by tomo-nagae** [comment]
@itoshot 
各バッチ毎にissueに起票いたしましたので本issueはクローズいたします。
◆Region改定再同意依頼バッチに関する質問 #18
https://github.com/Personal-Data-Linkage-Module/pxr-ver-1.0/issues/18
◆Book自動閉鎖バッチに関する質問 #19
https://github.com/Personal-Data-Linkage-Module/pxr-ver-1.0/issues/19
◆Region利用自動終了対象追加バッチに関する質問 #20
https://github.com/Personal-Data-Linkage-Module/pxr-ver-1.0/issues/20
◆Region利用自動終了バッチに関する質問 #21
https://github.com/Personal-Data-Linkage-Module/pxr-ver-1.0/issues/21
◆出力データファイル管理作成バッチに関する質問 #22
https://github.com/Personal-Data-Linkage-Module/pxr-ver-1.0/issues/22
◆Region終了対象追加バッチに関する質問 #23
https://github.com/Personal-Data-Linkage-Module/pxr-ver-1.0/issues/23
◆Region利用終了バッチに関する質問 #24
https://github.com/Personal-Data-Linkage-Module/pxr-ver-1.0/issues/24
